#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LB.Resource", IsApplication=true)]

namespace LB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LB.Core.Resource.String.library_name = global::LB.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_ab_back_holo_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int lb = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int red_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int reset = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int MainTitlebar = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int SubTitlebar = 2131099675;
			
			// aapt resource value: 0x7f060009
			public const int btnPhaseNext = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int btnPhasePrev = 2131099655;
			
			// aapt resource value: 0x7f060020
			public const int btnReset = 2131099680;
			
			// aapt resource value: 0x7f060004
			public const int btnTurnNext = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int btnTurnPrev = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int button1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button2 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int button3 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int button4 = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int includeBattleTitlebar = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int includeMainTitlebar = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int layoutActions = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int layoutActions1 = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int layoutActions2 = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int layoutPhase = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int layoutTurn = 2131099649;
			
			// aapt resource value: 0x7f060015
			public const int listBattles = 2131099669;
			
			// aapt resource value: 0x7f060005
			public const int space1 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int space2 = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int textDate = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int textName = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int textPhase = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int textPublisher = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int textTurn = 2131099651;
			
			// aapt resource value: 0x7f060017
			public const int titleMainLb = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int titleMainLeft = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int titleMainRight = 2131099673;
			
			// aapt resource value: 0x7f06001e
			public const int titleSubBattleName = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int titleSubLb = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int titleSubLbBack = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int titleSubScenarioName = 2131099679;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Battle = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BattleListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainTitlebar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScenarioListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SubTitlebar = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int reset = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int titleAsst = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int titleLaBat = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MainTitleBarStyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SubTitleBarStyle = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int button_reset_text = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int button_text = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
