#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LB.Resource", IsApplication=true)]

namespace LB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LB.Core.Resource.String.library_name = global::LB.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ambulance = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int attacker = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blackr1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int blackr2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blackr3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blackr4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int blackr5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blackr6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int blackw1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blackw2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int blackw3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int blackw4 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int blackw5 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int blackw6 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int blue1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int blue2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int blue3 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int blue4 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int blue5 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int blue6 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int blue_button = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int border = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int capture = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int defender = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int dice = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int fire = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_ab_back_holo_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int lb = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int melee = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int morale = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int red_button = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int redw1 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int redw2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int redw3 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int redw4 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int redw5 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int redw6 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int reset = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tombstone = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int whiteb1 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int whiteb2 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int whiteb3 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int whiteb4 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int whiteb5 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int whiteb6 = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int BattleTitlebar = 2131165204;
			
			// aapt resource value: 0x7f070052
			public const int MainTitlebar = 2131165266;
			
			// aapt resource value: 0x7f0700bd
			public const int SubTitlebar = 2131165373;
			
			// aapt resource value: 0x7f07000d
			public const int btnFire = 2131165197;
			
			// aapt resource value: 0x7f070025
			public const int btnFireAttacker12 = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int btnFireAttacker13 = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int btnFireAttacker32 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int btnFireAttackerCann = 2131165223;
			
			// aapt resource value: 0x7f070022
			public const int btnFireAttackerNext = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int btnFireAttackerPrev = 2131165215;
			
			// aapt resource value: 0x7f070033
			public const int btnFireDefenderIncrNext = 2131165235;
			
			// aapt resource value: 0x7f070030
			public const int btnFireDefenderIncrPrev = 2131165232;
			
			// aapt resource value: 0x7f07002e
			public const int btnFireDefenderNext = 2131165230;
			
			// aapt resource value: 0x7f07002b
			public const int btnFireDefenderPrev = 2131165227;
			
			// aapt resource value: 0x7f07003e
			public const int btnFireDiceRoll = 2131165246;
			
			// aapt resource value: 0x7f070011
			public const int btnGeneral = 2131165201;
			
			// aapt resource value: 0x7f07004f
			public const int btnGeneral1DiceRoll = 2131165263;
			
			// aapt resource value: 0x7f07004a
			public const int btnGeneral2DiceRoll = 2131165258;
			
			// aapt resource value: 0x7f07000e
			public const int btnMelee = 2131165198;
			
			// aapt resource value: 0x7f070060
			public const int btnMeleeAttackerAdd = 2131165280;
			
			// aapt resource value: 0x7f07005e
			public const int btnMeleeAttackerNext = 2131165278;
			
			// aapt resource value: 0x7f07005b
			public const int btnMeleeAttackerPrev = 2131165275;
			
			// aapt resource value: 0x7f070061
			public const int btnMeleeAttackerReset = 2131165281;
			
			// aapt resource value: 0x7f07006b
			public const int btnMeleeDefenderAdd = 2131165291;
			
			// aapt resource value: 0x7f070069
			public const int btnMeleeDefenderNext = 2131165289;
			
			// aapt resource value: 0x7f070066
			public const int btnMeleeDefenderPrev = 2131165286;
			
			// aapt resource value: 0x7f07006c
			public const int btnMeleeDefenderReset = 2131165292;
			
			// aapt resource value: 0x7f070078
			public const int btnMeleeDiceRoll = 2131165304;
			
			// aapt resource value: 0x7f070088
			public const int btnMeleeIncrNext = 2131165320;
			
			// aapt resource value: 0x7f070085
			public const int btnMeleeIncrPrev = 2131165317;
			
			// aapt resource value: 0x7f070097
			public const int btnMeleeLanceNext = 2131165335;
			
			// aapt resource value: 0x7f070094
			public const int btnMeleeLancePrev = 2131165332;
			
			// aapt resource value: 0x7f07008d
			public const int btnMeleeLossNext = 2131165325;
			
			// aapt resource value: 0x7f07008a
			public const int btnMeleeLossPrev = 2131165322;
			
			// aapt resource value: 0x7f0700a0
			public const int btnMeleeMods12 = 2131165344;
			
			// aapt resource value: 0x7f07009f
			public const int btnMeleeMods13 = 2131165343;
			
			// aapt resource value: 0x7f0700a2
			public const int btnMeleeMods2 = 2131165346;
			
			// aapt resource value: 0x7f0700a1
			public const int btnMeleeMods32 = 2131165345;
			
			// aapt resource value: 0x7f0700a3
			public const int btnMeleeModsLnc = 2131165347;
			
			// aapt resource value: 0x7f07009c
			public const int btnMeleeTotalNext = 2131165340;
			
			// aapt resource value: 0x7f070099
			public const int btnMeleeTotalPrev = 2131165337;
			
			// aapt resource value: 0x7f070092
			public const int btnMeleeValueNext = 2131165330;
			
			// aapt resource value: 0x7f07008f
			public const int btnMeleeValuePrev = 2131165327;
			
			// aapt resource value: 0x7f070010
			public const int btnMorale = 2131165200;
			
			// aapt resource value: 0x7f0700ae
			public const int btnMoraleDiceRoll = 2131165358;
			
			// aapt resource value: 0x7f0700b2
			public const int btnMoraleMinus1 = 2131165362;
			
			// aapt resource value: 0x7f0700b1
			public const int btnMoraleMinus3 = 2131165361;
			
			// aapt resource value: 0x7f0700b0
			public const int btnMoraleMinus6 = 2131165360;
			
			// aapt resource value: 0x7f0700a9
			public const int btnMoraleNext = 2131165353;
			
			// aapt resource value: 0x7f0700b4
			public const int btnMoralePlus1 = 2131165364;
			
			// aapt resource value: 0x7f0700b5
			public const int btnMoralePlus3 = 2131165365;
			
			// aapt resource value: 0x7f0700b7
			public const int btnMoralePlus6 = 2131165367;
			
			// aapt resource value: 0x7f0700a6
			public const int btnMoralePrev = 2131165350;
			
			// aapt resource value: 0x7f070009
			public const int btnPhaseNext = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int btnPhasePrev = 2131165191;
			
			// aapt resource value: 0x7f070019
			public const int btnReset = 2131165209;
			
			// aapt resource value: 0x7f070004
			public const int btnTurnNext = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int btnTurnPrev = 2131165186;
			
			// aapt resource value: 0x7f070062
			public const int editMeleeAttackerAdd = 2131165282;
			
			// aapt resource value: 0x7f07005d
			public const int editMeleeAttackerValue = 2131165277;
			
			// aapt resource value: 0x7f07006d
			public const int editMeleeDefenderAdd = 2131165293;
			
			// aapt resource value: 0x7f070068
			public const int editMeleeDefenderValue = 2131165288;
			
			// aapt resource value: 0x7f070087
			public const int editMeleeIncrValue = 2131165319;
			
			// aapt resource value: 0x7f070096
			public const int editMeleeLanceValue = 2131165334;
			
			// aapt resource value: 0x7f07008c
			public const int editMeleeLossValue = 2131165324;
			
			// aapt resource value: 0x7f07009b
			public const int editMeleeTotalValue = 2131165339;
			
			// aapt resource value: 0x7f070091
			public const int editMeleeValueValue = 2131165329;
			
			// aapt resource value: 0x7f0700a8
			public const int editMoraleValue = 2131165352;
			
			// aapt resource value: 0x7f070039
			public const int imgFireDie1 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int imgFireDie2 = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int imgFireDie3 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int imgFireDie4 = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int imgFireDie5 = 2131165245;
			
			// aapt resource value: 0x7f070045
			public const int imgFireLeaderLoss = 2131165253;
			
			// aapt resource value: 0x7f070043
			public const int imgFireLeaderLossSide = 2131165251;
			
			// aapt resource value: 0x7f07004d
			public const int imgGeneral1Die1 = 2131165261;
			
			// aapt resource value: 0x7f070048
			public const int imgGeneral2Die1 = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int imgGeneral2Die2 = 2131165257;
			
			// aapt resource value: 0x7f070073
			public const int imgMeleeDie1 = 2131165299;
			
			// aapt resource value: 0x7f070074
			public const int imgMeleeDie2 = 2131165300;
			
			// aapt resource value: 0x7f070075
			public const int imgMeleeDie3 = 2131165301;
			
			// aapt resource value: 0x7f070076
			public const int imgMeleeDie4 = 2131165302;
			
			// aapt resource value: 0x7f070077
			public const int imgMeleeDie5 = 2131165303;
			
			// aapt resource value: 0x7f07007f
			public const int imgMeleeLeaderLoss = 2131165311;
			
			// aapt resource value: 0x7f07007d
			public const int imgMeleeLeaderLossSide = 2131165309;
			
			// aapt resource value: 0x7f0700ac
			public const int imgMoraleDie1 = 2131165356;
			
			// aapt resource value: 0x7f0700ad
			public const int imgMoraleDie2 = 2131165357;
			
			// aapt resource value: 0x7f070000
			public const int includeBattleTitlebar = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int includeFireTitlebar = 2131165210;
			
			// aapt resource value: 0x7f070046
			public const int includeGeneralTitlebar = 2131165254;
			
			// aapt resource value: 0x7f070050
			public const int includeMainTitlebar = 2131165264;
			
			// aapt resource value: 0x7f070056
			public const int includeMeleeTitlebar = 2131165270;
			
			// aapt resource value: 0x7f0700a4
			public const int includeMoraleTitlebar = 2131165348;
			
			// aapt resource value: 0x7f07000b
			public const int layoutActions = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int layoutActions1 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int layoutActions2 = 2131165199;
			
			// aapt resource value: 0x7f07001c
			public const int layoutFireAttacker = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int layoutFireAttackerDefender = 2131165211;
			
			// aapt resource value: 0x7f070023
			public const int layoutFireAttackerMods = 2131165219;
			
			// aapt resource value: 0x7f07001e
			public const int layoutFireAttackerValue = 2131165214;
			
			// aapt resource value: 0x7f070028
			public const int layoutFireDefender = 2131165224;
			
			// aapt resource value: 0x7f07002f
			public const int layoutFireDefenderIncr = 2131165231;
			
			// aapt resource value: 0x7f07002a
			public const int layoutFireDefenderValue = 2131165226;
			
			// aapt resource value: 0x7f070038
			public const int layoutFireDice = 2131165240;
			
			// aapt resource value: 0x7f070034
			public const int layoutFireOdds = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int layoutFireOddsSelect = 2131165237;
			
			// aapt resource value: 0x7f07003f
			public const int layoutFireResults = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int layoutFireResults2 = 2131165248;
			
			// aapt resource value: 0x7f07004c
			public const int layoutGeneral1Dice = 2131165260;
			
			// aapt resource value: 0x7f070047
			public const int layoutGeneral2Dice = 2131165255;
			
			// aapt resource value: 0x7f070058
			public const int layoutMeleeAttacker = 2131165272;
			
			// aapt resource value: 0x7f070057
			public const int layoutMeleeAttackerDefender = 2131165271;
			
			// aapt resource value: 0x7f07005f
			public const int layoutMeleeAttackerMods = 2131165279;
			
			// aapt resource value: 0x7f07005a
			public const int layoutMeleeAttackerValue = 2131165274;
			
			// aapt resource value: 0x7f070081
			public const int layoutMeleeCalc = 2131165313;
			
			// aapt resource value: 0x7f070080
			public const int layoutMeleeCalculate = 2131165312;
			
			// aapt resource value: 0x7f070063
			public const int layoutMeleeDefender = 2131165283;
			
			// aapt resource value: 0x7f07006a
			public const int layoutMeleeDefenderMods = 2131165290;
			
			// aapt resource value: 0x7f070065
			public const int layoutMeleeDefenderValue = 2131165285;
			
			// aapt resource value: 0x7f070072
			public const int layoutMeleeDice = 2131165298;
			
			// aapt resource value: 0x7f07009d
			public const int layoutMeleeMods = 2131165341;
			
			// aapt resource value: 0x7f07006e
			public const int layoutMeleeOdds = 2131165294;
			
			// aapt resource value: 0x7f07006f
			public const int layoutMeleeOddsSelect = 2131165295;
			
			// aapt resource value: 0x7f070079
			public const int layoutMeleeResults = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int layoutMeleeResults2 = 2131165306;
			
			// aapt resource value: 0x7f070084
			public const int layoutMeleeUnitIncr = 2131165316;
			
			// aapt resource value: 0x7f070093
			public const int layoutMeleeUnitLance = 2131165331;
			
			// aapt resource value: 0x7f070089
			public const int layoutMeleeUnitLoss = 2131165321;
			
			// aapt resource value: 0x7f070098
			public const int layoutMeleeUnitTotal = 2131165336;
			
			// aapt resource value: 0x7f07008e
			public const int layoutMeleeUnitValue = 2131165326;
			
			// aapt resource value: 0x7f070082
			public const int layoutMeleeUnitValues = 2131165314;
			
			// aapt resource value: 0x7f0700ab
			public const int layoutMoraleDice = 2131165355;
			
			// aapt resource value: 0x7f0700af
			public const int layoutMoraleMods = 2131165359;
			
			// aapt resource value: 0x7f0700b9
			public const int layoutMoraleResults = 2131165369;
			
			// aapt resource value: 0x7f0700a5
			public const int layoutMoraleValue = 2131165349;
			
			// aapt resource value: 0x7f070006
			public const int layoutPhase = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int layoutTurn = 2131165185;
			
			// aapt resource value: 0x7f070020
			public const int lblFireAttackerValue = 2131165216;
			
			// aapt resource value: 0x7f070031
			public const int lblFireDefenderIncr = 2131165233;
			
			// aapt resource value: 0x7f07002c
			public const int lblFireDefenderValue = 2131165228;
			
			// aapt resource value: 0x7f070037
			public const int lblFireOdds = 2131165239;
			
			// aapt resource value: 0x7f070041
			public const int lblFireResults = 2131165249;
			
			// aapt resource value: 0x7f07005c
			public const int lblMeleeAttackerValue = 2131165276;
			
			// aapt resource value: 0x7f070067
			public const int lblMeleeDefenderValue = 2131165287;
			
			// aapt resource value: 0x7f070086
			public const int lblMeleeIncrValue = 2131165318;
			
			// aapt resource value: 0x7f070095
			public const int lblMeleeLanceValue = 2131165333;
			
			// aapt resource value: 0x7f07008b
			public const int lblMeleeLossValue = 2131165323;
			
			// aapt resource value: 0x7f070071
			public const int lblMeleeOdds = 2131165297;
			
			// aapt resource value: 0x7f07007b
			public const int lblMeleeResults = 2131165307;
			
			// aapt resource value: 0x7f07009a
			public const int lblMeleeTotalValue = 2131165338;
			
			// aapt resource value: 0x7f070090
			public const int lblMeleeValueValue = 2131165328;
			
			// aapt resource value: 0x7f0700b3
			public const int lblMoraleDiv = 2131165363;
			
			// aapt resource value: 0x7f0700b6
			public const int lblMoralePlus1 = 2131165366;
			
			// aapt resource value: 0x7f0700b8
			public const int lblMoralePlus3 = 2131165368;
			
			// aapt resource value: 0x7f0700ba
			public const int lblMoraleResults = 2131165370;
			
			// aapt resource value: 0x7f0700a7
			public const int lblMoraleValue = 2131165351;
			
			// aapt resource value: 0x7f070051
			public const int listBattles = 2131165265;
			
			// aapt resource value: 0x7f07004b
			public const int moraleSpace0 = 2131165259;
			
			// aapt resource value: 0x7f07004e
			public const int moraleSpace1 = 2131165262;
			
			// aapt resource value: 0x7f070005
			public const int space1 = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int space2 = 2131165194;
			
			// aapt resource value: 0x7f070036
			public const int spinFireOdds = 2131165238;
			
			// aapt resource value: 0x7f070070
			public const int spinMeleeOdds = 2131165296;
			
			// aapt resource value: 0x7f0700bc
			public const int textDate = 2131165372;
			
			// aapt resource value: 0x7f070021
			public const int textFireAttackerValue = 2131165217;
			
			// aapt resource value: 0x7f070032
			public const int textFireDefenderIncr = 2131165234;
			
			// aapt resource value: 0x7f07002d
			public const int textFireDefenderValue = 2131165229;
			
			// aapt resource value: 0x7f0700aa
			public const int textMoraleValue = 2131165354;
			
			// aapt resource value: 0x7f070012
			public const int textName = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int textPhase = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int textPublisher = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int textTurn = 2131165187;
			
			// aapt resource value: 0x7f070053
			public const int titleMainLb = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int titleMainLeft = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int titleMainRight = 2131165269;
			
			// aapt resource value: 0x7f070017
			public const int titleSubBattleName = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int titleSubLb = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int titleSubLbBack = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int titleSubScenarioName = 2131165208;
			
			// aapt resource value: 0x7f07001d
			public const int txtFireAttacker = 2131165213;
			
			// aapt resource value: 0x7f070029
			public const int txtFireDefender = 2131165225;
			
			// aapt resource value: 0x7f070044
			public const int txtFireLeaderLoss = 2131165252;
			
			// aapt resource value: 0x7f070042
			public const int txtFireResults = 2131165250;
			
			// aapt resource value: 0x7f070059
			public const int txtMeleeAttacker = 2131165273;
			
			// aapt resource value: 0x7f070064
			public const int txtMeleeDefender = 2131165284;
			
			// aapt resource value: 0x7f07007e
			public const int txtMeleeLeaderLoss = 2131165310;
			
			// aapt resource value: 0x7f07009e
			public const int txtMeleeMods = 2131165342;
			
			// aapt resource value: 0x7f07007c
			public const int txtMeleeResults = 2131165308;
			
			// aapt resource value: 0x7f070083
			public const int txtMeleeUnit = 2131165315;
			
			// aapt resource value: 0x7f0700bb
			public const int txtMoraleResults = 2131165371;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Battle = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BattleListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BattleTitlebar = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FireCombat = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int General = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainTitlebar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Melee = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Morale = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ScenarioListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SubTitlebar = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int droll = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int reset = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int titleAsst = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int titleLaBat = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MainTitleBarStyle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int SubTitleBarStyle = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int button_reset_text = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int button_text = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int group_text = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int toggle_text = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
