#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LB.Resource", IsApplication=true)]

namespace LB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LB.Core.Resource.String.library_name = global::LB.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ambulance = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int attacker = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blackr1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int blackr2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blackr3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blackr4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int blackr5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blackr6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int blackw1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blackw2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int blackw3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int blackw4 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int blackw5 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int blackw6 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int blue1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int blue2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int blue3 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int blue4 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int blue5 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int blue6 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int blue_button = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int border = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int capture = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int defender = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_ab_back_holo_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int lb = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int red_button = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int redw1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int redw2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int redw3 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int redw4 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int redw5 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int redw6 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int reset = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tombstone = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int whiteb1 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int whiteb2 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int whiteb3 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int whiteb4 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int whiteb5 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int whiteb6 = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int BattleTitlebar = 2131165204;
			
			// aapt resource value: 0x7f070047
			public const int MainTitlebar = 2131165255;
			
			// aapt resource value: 0x7f07004c
			public const int SubTitlebar = 2131165260;
			
			// aapt resource value: 0x7f07000d
			public const int btnFire = 2131165197;
			
			// aapt resource value: 0x7f070024
			public const int btnFireAttacker12 = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int btnFireAttacker13 = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int btnFireAttacker32 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int btnFireAttackerCann = 2131165222;
			
			// aapt resource value: 0x7f070021
			public const int btnFireAttackerNext = 2131165217;
			
			// aapt resource value: 0x7f07001e
			public const int btnFireAttackerPrev = 2131165214;
			
			// aapt resource value: 0x7f070032
			public const int btnFireDefenderIncrNext = 2131165234;
			
			// aapt resource value: 0x7f07002f
			public const int btnFireDefenderIncrPrev = 2131165231;
			
			// aapt resource value: 0x7f07002d
			public const int btnFireDefenderNext = 2131165229;
			
			// aapt resource value: 0x7f07002a
			public const int btnFireDefenderPrev = 2131165226;
			
			// aapt resource value: 0x7f07003d
			public const int btnFireDiceRoll = 2131165245;
			
			// aapt resource value: 0x7f070011
			public const int btnGeneral = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int btnMelee = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int btnMorale = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int btnPhaseNext = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int btnPhasePrev = 2131165191;
			
			// aapt resource value: 0x7f070019
			public const int btnReset = 2131165209;
			
			// aapt resource value: 0x7f070004
			public const int btnTurnNext = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int btnTurnPrev = 2131165186;
			
			// aapt resource value: 0x7f070038
			public const int imgFireDie1 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int imgFireDie2 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int imgFireDie3 = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int imgFireDie4 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int imgFireDie5 = 2131165244;
			
			// aapt resource value: 0x7f070044
			public const int imgFireLeaderLoss = 2131165252;
			
			// aapt resource value: 0x7f070042
			public const int imgFireLeaderLossSide = 2131165250;
			
			// aapt resource value: 0x7f070000
			public const int includeBattleTitlebar = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int includeFireTitlebar = 2131165210;
			
			// aapt resource value: 0x7f070045
			public const int includeMainTitlebar = 2131165253;
			
			// aapt resource value: 0x7f07000b
			public const int layoutActions = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int layoutActions1 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int layoutActions2 = 2131165199;
			
			// aapt resource value: 0x7f07001b
			public const int layoutFireAttacker = 2131165211;
			
			// aapt resource value: 0x7f070022
			public const int layoutFireAttackerMods = 2131165218;
			
			// aapt resource value: 0x7f07001d
			public const int layoutFireAttackerValue = 2131165213;
			
			// aapt resource value: 0x7f070027
			public const int layoutFireDefender = 2131165223;
			
			// aapt resource value: 0x7f07002e
			public const int layoutFireDefenderIncr = 2131165230;
			
			// aapt resource value: 0x7f070029
			public const int layoutFireDefenderValue = 2131165225;
			
			// aapt resource value: 0x7f070037
			public const int layoutFireDice = 2131165239;
			
			// aapt resource value: 0x7f070033
			public const int layoutFireOdds = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int layoutFireOddsSelect = 2131165236;
			
			// aapt resource value: 0x7f07003e
			public const int layoutFireResults = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int layoutFireResults2 = 2131165247;
			
			// aapt resource value: 0x7f070006
			public const int layoutPhase = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int layoutTurn = 2131165185;
			
			// aapt resource value: 0x7f07001f
			public const int lblFireAttackerValue = 2131165215;
			
			// aapt resource value: 0x7f070030
			public const int lblFireDefenderIncr = 2131165232;
			
			// aapt resource value: 0x7f07002b
			public const int lblFireDefenderValue = 2131165227;
			
			// aapt resource value: 0x7f070036
			public const int lblFireOdds = 2131165238;
			
			// aapt resource value: 0x7f070040
			public const int lblFireResults = 2131165248;
			
			// aapt resource value: 0x7f070046
			public const int listBattles = 2131165254;
			
			// aapt resource value: 0x7f070005
			public const int space1 = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int space2 = 2131165194;
			
			// aapt resource value: 0x7f070035
			public const int spinFireOdds = 2131165237;
			
			// aapt resource value: 0x7f07004b
			public const int textDate = 2131165259;
			
			// aapt resource value: 0x7f070020
			public const int textFireAttackerValue = 2131165216;
			
			// aapt resource value: 0x7f070031
			public const int textFireDefenderIncr = 2131165233;
			
			// aapt resource value: 0x7f07002c
			public const int textFireDefenderValue = 2131165228;
			
			// aapt resource value: 0x7f070012
			public const int textName = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int textPhase = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int textPublisher = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int textTurn = 2131165187;
			
			// aapt resource value: 0x7f070048
			public const int titleMainLb = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int titleMainLeft = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int titleMainRight = 2131165258;
			
			// aapt resource value: 0x7f070017
			public const int titleSubBattleName = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int titleSubLb = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int titleSubLbBack = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int titleSubScenarioName = 2131165208;
			
			// aapt resource value: 0x7f07001c
			public const int txtFireAttacker = 2131165212;
			
			// aapt resource value: 0x7f070028
			public const int txtFireDefender = 2131165224;
			
			// aapt resource value: 0x7f070043
			public const int txtFireLeaderLoss = 2131165251;
			
			// aapt resource value: 0x7f070041
			public const int txtFireResults = 2131165249;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Battle = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BattleListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BattleTitlebar = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FireCombat = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainTitlebar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ScenarioListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SubTitlebar = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int droll = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int reset = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int titleAsst = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int titleLaBat = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MainTitleBarStyle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int SubTitleBarStyle = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int button_reset_text = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int button_text = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int group_text = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int toggle_text = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
